services:
  db:
    restart: always
    image: postgres:15
    environment:
      POSTGRES_USER: cascade
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: cascade
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgbackups:/backups
    ports:
      - 5433:5432
    secrets:
      - db_password

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - pgbackups:/backups
    links:
      - db
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=cascade
      - POSTGRES_USER=cascade
      - POSTGRES_PASSWORD=cascade
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=@every 1m1s #@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080
    secrets:
      - db_password

  app:
    restart: always
    image: cascadelab.azurecr.io/cascade-lab/cascade/prod:v3.7
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cascade
      SPRING_DATASOURCE_USERNAME: cascade
      SPRING_DATASOURCE_PASSWORD_FILE: /run/secrets/db_password
      CUSTOM_CONTAINER_MODE_ENABLED: true
    volumes:
      - app-data:/app/storage
    ports:
      - 8080:8080
    secrets:
      - db_password

secrets:
   db_password:
     file: ./db_password.txt

volumes:
  db-data:
  app-data:
  pgbackups: