version: '4.3'

services:
  db:
    user: "${CURRENT_UID}:${CURRENT_GID}"
    restart: always
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./0-init-database.sh:/docker-entrypoint-initdb.d/0-init-database.sh
    ports:
      - 5432:5432
    secrets:
      - db_password

  app:
    restart: always
    image: cascadelab.azurecr.io/cascade-lab/cascade/prod:v4.3.0
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cascade
      SPRING_DATASOURCE_USERNAME: cascade
      SPRING_DATASOURCE_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - app-data:/app/storage
    ports:
      - 8080:8080
    secrets:
      - db_password

secrets:
   db_password:
     file: ./db_password.txt

volumes:
  db-data:
    driver_opts:
      type: none
      o: bind
      device: /home/azureuser/cascade-docker/data/db
  app-data:
    driver_opts:
      type: none
      o: bind
      device: /home/azureuser/cascade-docker/data/documents
